- name: disable default nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable nodejs 20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present
- name: Install npm explicitly
  ansible.builtin.package:
    name: npm
    state: present    
- name: install dependencies
  community.general.npm:
    path: /app
  tags:
  - deployment