$ANSIBLE_VAULT;1.1;AES256
33343565343431306366393831353163633535356562343164363165326466353062643762643733
3736363032323936396161633333383134396164633163330a643135663066326532343130343764
34623132313563356432643033633664323134666162623063303335646339353331313132383938
3938346531373535660a636462346537613739646634393536613333363932393833643439303861
35653161643363646335656634636438363438356237376437303937363839626263366233383662
3536333061386233646332636131386333303964653461626666